export default {
    APPLICATION_STATE: 'APPLICATION_STATE',
    
    ZONES_RECEIVED: 'ZONES_RECEIVED',
    ZONE_CREATE: 'ZONE_CREATE',
    ZONE_SELECTED: 'ZONE_SELECTED',
    
    // current logged in user
    CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
    USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',

    // profile info for any user
    USER_RECEIVED: 'USER_RECEIVED'

}